CREATE TABLE  `E_BOOK` 
   (	`CALLNO` VARCHAR(4000), 
	`NAME` VARCHAR(4000), 
	`AUTHOR` VARCHAR(4000), 
	`PUBLISHER` VARCHAR(4000), 
	`QUANTITY` DOUBLE, 
	`ISSUED` DOUBLE, 
	 CONSTRAINT `E_BOOK_PK` PRIMARY KEY (`CALLNO`) 
   );

CREATE TABLE  `E_LIBRARIAN` 
   (	`ID` DOUBLE, 
	`NAME` VARCHAR(4000), 
	`PASSWORD` VARCHAR(4000), 
	`EMAIL` VARCHAR(4000), 
	`MOBILE` DOUBLE, 
	 CONSTRAINT `E_LIBRARIAN_PK` PRIMARY KEY (`ID`) 
   );

CREATE TABLE  `E_ISSUEBOOK` 
   (	`CALLNO` VARCHAR(4000) NOT NULL, 
	`STUDENTID` VARCHAR(4000) NOT NULL, 
	`STUDENTNAME` VARCHAR(4000), 
	`STUDENTMOBILE` DOUBLE, 
	`ISSUEDDATE` DATETIME, 
	`RETURNSTATUS` VARCHAR(4000)
   );